apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cassandra-3h
spec:
  schedule: "10 */3 * * *"
  successfulJobsHistoryLimit: 0
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:          
            type: backup
            workload: cassandra           
        spec:  
          nodeSelector:
            role: cassandra
            cassandraNode: "1"
          containers:
          - name: cassandra-backup-pod-3h
            image: vdubovyk/k8s-backup-test
            imagePullPolicy: Always
            env:
              - name: WEBHOOK
                value: YOUR_WEBHOOK
              - name: CQLSH_HOST
                value: cassandra
              - name: DB
                value: /var/lib/cassandra/data/thingsboard/
              - name: DATASTORE
                value: /data/
            command:
              - /bin/bash
              - -c
              - /home/root/backupCassandra_3h.sh
            volumeMounts:
              - name: cassandra-data
                mountPath: /var/lib/cassandra
              - name: datastore
                mountPath: /data
          volumes:
            - name: cassandra-data
              persistentVolumeClaim:
                claimName: cassandra-data-cassandra-0
            - name: datastore
              persistentVolumeClaim:
                claimName: tb-backup
          restartPolicy: Never
