apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backup-viewer-pod
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: backup-viewer-pod
          image: vdubovyk/k8s-backup
          imagePullPolicy: Always
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
            - name: datastore
              mountPath: /data
        volumes:
          - name: cassandra-data
            persistentVolumeClaim:
              claimName: cassandra-data-cassandra-0
          - name: datastore
            persistentVolumeClaim:
              claimName: tb-backup

        restartPolicy: OnFailure
