---
apiVersion: v1
kind: Pod
metadata:
  name: view-pod
  namespace: thingsboard
spec:
  nodeSelector:
    role: cassandra
    cassandraNode: "1"
  containers:
  - name: cassandra-backup
    image: vdubovyk/k8s-backup-test
    imagePullPolicy: Always
    env:
      - name: WEBHOOK
        value: YOUR_WEBHOOK_ENDPOINT
      - name: CQLSH_HOST
        value: cassandra
      - name: DB
        value: /var/lib/cassandra/data/thingsboard/
    command:
      - /bin/bash
      - -c 
      - sleep 25000
    volumeMounts:
      - name: cassandra-data
        mountPath: /var/lib/cassandra
      - name: datastore
        mountPath: /data
  volumes:
    - name: cassandra-data
      persistentVolumeClaim:
        claimName: cassandra-data-cassandra-0
    - name: datastore
      persistentVolumeClaim:
        claimName: tb-backup
  restartPolicy: Never
